/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sig.view;

import com.sig.controller.Controller;
import com.sig.model.InvoiceHeader;
import com.sig.model.InvoiceTableItemModel;
import com.sig.model.LineItemTableModel;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author sara
 */
public class InvoicesFrame extends javax.swing.JFrame {

    
    private ArrayList<InvoiceHeader> invoicesList;
    private Controller controller = new  Controller(this);

   
    private InvoiceTableItemModel invoiceTableModel  = controller.getInvoicesTableModel();
    private LineItemTableModel lineTableModel;

    
    
    /**
     */
    public InvoicesFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        invoicesTable = new javax.swing.JTable();
        invoicesTable.setModel(invoiceTableModel);
        invoicesTable.getSelectionModel().addListSelectionListener(controller);
        jScrollPane2 = new javax.swing.JScrollPane();
        linesTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        invoiceNumLabel = new javax.swing.JLabel();
        invoiceDateField = new javax.swing.JTextField();
        customerNameField = new javax.swing.JTextField();
        invoiceTotalLabel = new javax.swing.JLabel();
        saveInvoiceBtn = new javax.swing.JButton();
        saveInvoiceBtn.addActionListener(this.controller);
        deleteInvoceBtn = new javax.swing.JButton();
        deleteInvoceBtn.addActionListener(this.controller);
        DeleteLineBtn = new javax.swing.JButton();
        DeleteLineBtn.addActionListener(this.controller);
        createInvoiceBtn = new javax.swing.JButton();
        createInvoiceBtn.addActionListener(this.controller);
        jMenuBar1 = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenu1 = new javax.swing.JMenu();
        loadFileItem = new javax.swing.JMenuItem();
        loadFileItem.addActionListener(this.controller);
        saveFileItem = new javax.swing.JMenuItem();
        saveFileItem.addActionListener(this.controller);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        invoicesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(invoicesTable);

        linesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(linesTable);

        jLabel1.setText("Invoice number:");

        jLabel2.setText("Invoice Date:");

        jLabel3.setText("Customer Name:");

        jLabel4.setText("Invoice Total:");

        saveInvoiceBtn.setText("Create new line");
        saveInvoiceBtn.setActionCommand("Save Invoice changes");

        deleteInvoceBtn.setText("Delete Invoice");

        DeleteLineBtn.setActionCommand("delete Invoice Line");
        DeleteLineBtn.setLabel("Delete line item");

        createInvoiceBtn.setText("Create New Invoice");

        jMenu1.setText("File");

        loadFileItem.setText("Load file");
        jMenu1.add(loadFileItem);

        saveFileItem.setText("Save file");
        jMenu1.add(saveFileItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createInvoiceBtn)
                        .addGap(18, 18, 18)
                        .addComponent(deleteInvoceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(invoiceDateField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerNameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(invoiceNumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(invoiceTotalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(saveInvoiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DeleteLineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {DeleteLineBtn, createInvoiceBtn, deleteInvoceBtn, saveInvoiceBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(invoiceNumLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(invoiceDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(customerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(invoiceTotalLabel))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveInvoiceBtn)
                    .addComponent(deleteInvoceBtn)
                    .addComponent(DeleteLineBtn)
                    .addComponent(createInvoiceBtn))
                .addGap(41, 41, 41))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {DeleteLineBtn, createInvoiceBtn, deleteInvoceBtn, saveInvoiceBtn});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {customerNameField, invoiceDateField, invoiceNumLabel, invoiceTotalLabel, jLabel1, jLabel2, jLabel3, jLabel4});

        DeleteLineBtn.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public void setCustomerNameField(JTextField customerNameField) {
        this.customerNameField = customerNameField;
    }

    public void setInvoiceDateField(JTextField invoiceDateField) {
        this.invoiceDateField = invoiceDateField;
    }

    public JTextField getCustomerNameField() {
        return customerNameField;
    }

    public JTextField getInvoiceDateField() {
        return invoiceDateField;
    }

    public void setInvoiceNumLabel(JLabel invoiceNumLabel) {
        this.invoiceNumLabel = invoiceNumLabel;
    }

    public void setInvoiceTotalLabel(JLabel invoiceTotalLabel) {
        this.invoiceTotalLabel = invoiceTotalLabel;
    }
    
    public Controller getController() {
        return controller;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteLineBtn;
    private javax.swing.JButton createInvoiceBtn;
    private javax.swing.JTextField customerNameField;
    private javax.swing.JButton deleteInvoceBtn;
    private javax.swing.JTextField invoiceDateField;
    private javax.swing.JLabel invoiceNumLabel;
    private javax.swing.JLabel invoiceTotalLabel;
    private javax.swing.JTable invoicesTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable linesTable;
    private javax.swing.JMenuItem loadFileItem;
    private javax.swing.JMenuItem saveFileItem;
    private javax.swing.JButton saveInvoiceBtn;
    // End of variables declaration//GEN-END:variables
    
    
  

    public void setInvoicesList(ArrayList<InvoiceHeader> invoicesList) {
        this.invoicesList = invoicesList;
    }

    public ArrayList<InvoiceHeader> getInvoicesList() {
        return invoicesList;
    }

    public JTable getInvoicesTable() {
        return invoicesTable;
    }

    public JTable getLinesTable() {
        return linesTable;
    }

    public void setLinesTable(JTable linesTable) {
        this.linesTable = linesTable;
    }

    public void setInvoiceTotal(JLabel invoiceTotal) {
        this.invoiceTotalLabel = invoiceTotal;
    }
    public void setLineTableModel(LineItemTableModel lineTableModel) {
        this.lineTableModel = lineTableModel;
    }

    public LineItemTableModel getLineTableModel() {
        return lineTableModel;
    }
    public void updateInvoiceUI(InvoiceHeader invoice){
        invoiceNumLabel.setText(Integer.toString(invoice.getInvoiceNumber()) );
        customerNameField.setText(invoice.getCustomerName());
        invoiceDateField.setText(invoice.getInvoiceDateString());
        invoiceTotalLabel.setText(invoice.getInvoiceTotal().toString());
        
    }
    
     
    
public static void main(String args[]) {
         

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoicesFrame().setVisible(true);
            }
        });
    }
}
